<?php $isEdit = !empty($edit); ?>
<h1>Inventário</h1>
<div class="btn-group-responsive mb-3"><a class="btn btn-success" href="<?= \App\Core\Url::page('export_excel') ?>" title="Export Excel/CSV" aria-label="Export Excel/CSV"><i class="bi bi-file-earmark-spreadsheet"></i></a><a class="btn btn-danger" href="<?= \App\Core\Url::page('export_pdf') ?>" title="Export PDF" aria-label="Export PDF"><i class="bi bi-file-earmark-pdf"></i></a></div>
<form method="post" action="<?= \App\Core\Url::page('inventory_save') ?>" class="row g-2 quick-form mb-4">
    <?php if ($isEdit): ?><input type="hidden" name="id" value="<?= (int)$edit['id'] ?>"><?php endif; ?>
    <div class="col-md-3"><select class="form-select" name="item_id"><?php foreach($items as $i): ?><option value="<?= $i['id'] ?>" <?= (int)($edit['item_id'] ?? 0) === (int)$i['id'] ? 'selected' : '' ?>><?= htmlspecialchars($i['name']) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-3"><select class="form-select" name="warehouse_id"><?php foreach($warehouses as $w): ?><option value="<?= $w['id'] ?>" <?= (int)($edit['warehouse_id'] ?? 0) === (int)$w['id'] ? 'selected' : '' ?>><?= htmlspecialchars($w['name'].' · '.$w['section']) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-2"><input class="form-control" name="quantity" type="number" step="0.01" placeholder="Qtd" value="<?= htmlspecialchars($edit['quantity'] ?? '') ?>" required></div>
    <div class="col-md-2"><input class="form-control" name="min_quantity" type="number" step="0.01" placeholder="Mínimo" value="<?= htmlspecialchars($edit['min_quantity'] ?? '') ?>" required></div>
    <div class="col-md-2"><button class="btn btn-primary w-100" title="Guardar stock" aria-label="Guardar stock"><i class="bi bi-save"></i></button></div>
</form>
<div class="table-responsive"><table class="table align-middle"><tr><th>Artigo</th><th>Armazém</th><th>Qtd</th><th>Mín.</th><th>Valor</th><th>Ações</th></tr><?php foreach($rows as $r): ?><tr class="<?= $r['quantity'] <= $r['min_quantity'] ? 'table-warning' : '' ?>"><td><?= htmlspecialchars($r['item']) ?></td><td><?= htmlspecialchars($r['warehouse']) ?></td><td><?= htmlspecialchars($r['quantity'].' '.$r['unit']) ?></td><td><?= htmlspecialchars($r['min_quantity']) ?></td><td>€ <?= number_format((float)$r['stock_value'],2,',','.') ?></td><td><a class="btn btn-sm btn-outline-primary" href="<?= \App\Core\Url::page('inventory') ?>&edit=<?= $r['id'] ?>" title="Editar" aria-label="Editar"><i class="bi bi-pencil"></i></a> <a class="btn btn-sm btn-outline-danger" href="<?= \App\Core\Url::page('inventory') ?>&delete=<?= $r['id'] ?>" onclick="return confirm('Apagar stock?')" title="Apagar" aria-label="Apagar"><i class="bi bi-trash"></i></a></td></tr><?php endforeach; ?></table></div>
