<?php use App\Core\Url; $admitted = count(array_filter($reservations, fn($r) => !empty($r['admitted_at']))); ?>
<div class="admissions-shell">
    <div class="admissions-top"><div class="admissions-brand"><span><i class="bi bi-upc-scan"></i></span><div><strong>Admissões</strong><small><?= date('d/m/Y') ?></small></div></div><a class="btn btn-light" href="<?= Url::page('admissions_logout') ?>"><i class="bi bi-box-arrow-right"></i> Sair</a></div>
    <?php if (!$event): ?><div class="event-public-card text-center"><i class="bi bi-calendar-x display-4 text-muted"></i><h1 class="h3 mt-3">Sem evento agendado para hoje</h1><p class="text-muted mb-0">Esta página atualizar-se-á quando existir um evento.</p></div>
    <?php else: ?>
        <header class="admissions-event"><div><span class="eyebrow">Evento de hoje</span><h1><?= htmlspecialchars($event['title']) ?></h1><p><i class="bi bi-clock"></i> <?= date('H:i', strtotime($event['starts_at'])) ?> &nbsp; <i class="bi bi-geo-alt"></i> <?= htmlspecialchars($event['venue']) ?></p></div><div class="admissions-count"><strong><?= $admitted ?></strong><span>de <?= count($reservations) ?> entradas</span></div></header>
        <div class="event-public-card"><div class="section-title"><h2>Lista de reservas</h2><span class="soft-badge"><?= array_sum(array_map(fn($r)=>(int)$r['tickets'], $reservations)) ?> bilhetes</span></div>
            <div class="admissions-list"><?php foreach ($reservations as $reservation): ?><article class="admission-row <?= $reservation['admitted_at'] ? 'is-admitted' : '' ?>"><div class="admission-avatar"><?= htmlspecialchars(mb_strtoupper(mb_substr($reservation['customer_name'], 0, 1))) ?></div><div class="admission-person"><strong><?= htmlspecialchars($reservation['customer_name']) ?></strong><span><?= htmlspecialchars($reservation['customer_email']) ?> · <?= (int)$reservation['tickets'] ?> bilhete(s)</span></div><?php if ($reservation['admitted_at']): ?><span class="admitted-label"><i class="bi bi-check-circle-fill"></i> Admitido</span><?php else: ?><form method="post" action="<?= Url::page('admit') ?>"><input type="hidden" name="event_id" value="<?= (int)$event['id'] ?>"><input type="hidden" name="reservation_id" value="<?= (int)$reservation['id'] ?>"><button class="btn btn-success" type="submit"><i class="bi bi-check2"></i> Admitir</button></form><?php endif; ?></article><?php endforeach; ?><?php if (!$reservations): ?><p class="text-muted text-center py-4 mb-0">Ainda não existem reservas para este evento.</p><?php endif; ?></div>
        </div>
    <?php endif; ?>
</div>
